# Service creation for load balancing
apiVersion: v1
kind: Service
metadata:
  name: java-kubernetes-demo
  labels:
    app: java-kubernetes-demo
spec:
  ports:
    - port: 80
      nodePort: 30001
      protocol: TCP
      name: http
  selector:
    app: java-kubernetes-demo
    tier: java-kubernetes-demo
  type: NodePort
---
# Deployment creation of the application
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: java-kubernetes-demo
  labels:
    app: java-kubernetes-demo
spec:
  selector:
    matchLabels:
      app: java-kubernetes-demo
      tier: java-kubernetes-demo
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: java-kubernetes-demo
        tier: java-kubernetes-demo
    spec:
      containers:
      - image: borre/java-kubernetes-demo
        name: java-kubernetes-demo
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: "150Mi"
          requests:
            cpu: "1"
            memory: "150Mi"
        ports:
        - containerPort: 80
---
# Exposing redis server
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - name: redis
    port: 6379
  clusterIP: None
  selector:
    app: redis
---
# Deployment creation of redis
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      tier: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
        tier: redis
    spec:
      containers:
      - image: redis
        name: redis
        imagePullPolicy: IfNotPresent
        env:
        ports:
        - containerPort: 6379
---
# Definition of the autoscaling policy 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: java-kubernetes-demo
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: java-kubernetes-demo
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20